[pytest]
addopts = -v --alluredir=allure-results
testpaths = tests
python_files = test_*.py

markers =
    db: tests que validan base de datos
    end_to_end: tests que prueban flujo completo API/UI/DB
    api: tests de API
    ui: tests de interfaz
    smoke: tests críticos y rápidos
    critical: tests de prioridad alta